/**
 * Inserts the initial structure into the database
 *
 * @package [Redacted]Me
 * ---------------------------------------------------------------------------
 *
 * Merchant Empires by [Redacted] Games LLC - A space merchant game of war
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 
-- MySQL Script generated by MySQL Workbench
-- 01/31/16 19:35:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spacegame
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `races`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `races` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `caption` VARCHAR(16) NOT NULL COMMENT '',
  `tax_rate` DECIMAL(3,1) NOT NULL DEFAULT 0.1 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  UNIQUE INDEX `caption_UNIQUE` (`caption` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alliances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alliances` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `caption` VARCHAR(24) NOT NULL COMMENT '',
  `tax_mult` DECIMAL(3,2) NULL DEFAULT '1.00' COMMENT 'Computed from the number of members for speed.',
  `founder` INT NOT NULL COMMENT '',
  `recruiting` INT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  UNIQUE INDEX `caption_UNIQUE` (`caption` ASC)  COMMENT '',
  INDEX `fkey_alliance_founder_idx` (`founder` ASC)  COMMENT '',
  CONSTRAINT `fkey_alliance_founder`
    FOREIGN KEY (`founder`)
    REFERENCES `players` (`record_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ranks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ranks` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `caption` VARCHAR(16) NOT NULL COMMENT '',
  `level` INT NULL DEFAULT 0 COMMENT '',
  `alignment` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  UNIQUE INDEX `caption_UNIQUE` (`caption` ASC)  COMMENT '',
  UNIQUE INDEX `alignment_UNIQUE` (`alignment` ASC)  COMMENT '',
  UNIQUE INDEX `level_UNIQUE` (`level` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ships` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `caption` VARCHAR(24) NULL COMMENT '',
  `race` INT NOT NULL COMMENT '',
  `rank` INT NOT NULL DEFAULT 1 COMMENT '',
  `holds` INT NOT NULL DEFAULT 100 COMMENT '',
  `shields` INT NOT NULL DEFAULT 100 COMMENT '',
  `armor` INT NOT NULL DEFAULT 100 COMMENT '',
  `tps` DECIMAL(3,1) NOT NULL DEFAULT '1.0' COMMENT '',
  `price` INT NULL DEFAULT 1000000 COMMENT '',
  `racks` INT NULL DEFAULT 0 COMMENT '',
  `stations` INT NULL DEFAULT 0 COMMENT '',
  `recharge` INT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fk_ship_race_idx` (`race` ASC)  COMMENT '',
  INDEX `idx_ship_level` (`rank` ASC)  COMMENT '',
  CONSTRAINT `fk_ship_race`
    FOREIGN KEY (`race`)
    REFERENCES `races` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ship_rank`
    FOREIGN KEY (`rank`)
    REFERENCES `ranks` (`record_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `players` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `caption` VARCHAR(16) NOT NULL COMMENT '',
  `x` INT NOT NULL DEFAULT 0 COMMENT '',
  `y` INT NOT NULL DEFAULT 0 COMMENT '',
  `death` INT NOT NULL DEFAULT 0 COMMENT 'Timestamp when death has occured or zero if player is still alive.',
  `race` INT NOT NULL DEFAULT 0 COMMENT '',
  `turns` DECIMAL(6,2) NOT NULL DEFAULT 0 COMMENT '',
  `ship_type` INT NULL DEFAULT NULL COMMENT '',
  `ship_name` VARCHAR(16) NULL COMMENT '',
  `credits` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  `alliance` INT NULL DEFAULT NULL COMMENT '',
  `experience` INT NULL DEFAULT 0 COMMENT '',
  `level` INT NULL DEFAULT 0 COMMENT '',
  `alignment` INT NULL DEFAULT 0 COMMENT '',
  `rank` INT NULL DEFAULT 1 COMMENT '',
  `last_turns` INT NULL DEFAULT 0 COMMENT '',
  `shields` INT NULL DEFAULT 0 COMMENT '',
  `armor` INT NULL DEFAULT 0 COMMENT '',
  `last_move` INT NULL DEFAULT 0 COMMENT '',
  `target_x` INT NULL DEFAULT 0 COMMENT '',
  `target_y` INT NULL DEFAULT 0 COMMENT '',
  `target_type` INT NULL DEFAULT 0 COMMENT '',
  `base_id` INT NULL DEFAULT 0 COMMENT '',
  `base_x` INT NULL DEFAULT 0 COMMENT '',
  `base_y` INT NULL DEFAULT 0 COMMENT '',
  `last_alignment` INT NULL DEFAULT 0 COMMENT '',
  `gold_expiration` INT NULL DEFAULT 0 COMMENT '',
  `messages_read` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  UNIQUE INDEX `caption_UNIQUE` (`caption` ASC)  COMMENT '',
  INDEX `fk_player_races_idx` (`race` ASC)  COMMENT '',
  INDEX `fk_ship_type_idx` (`ship_type` ASC)  COMMENT '',
  INDEX `fk_player_xy` (`y` ASC, `x` ASC)  COMMENT '',
  INDEX `fk_player_alliance_idx` (`alliance` ASC)  COMMENT '',
  INDEX `fk_player_rank_idx` (`rank` ASC)  COMMENT '',
  CONSTRAINT `fk_player_races`
    FOREIGN KEY (`race`)
    REFERENCES `races` (`record_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_player_alliance`
    FOREIGN KEY (`alliance`)
    REFERENCES `alliances` (`record_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_player_rank`
    FOREIGN KEY (`rank`)
    REFERENCES `ranks` (`record_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ship_type`
    FOREIGN KEY (`ship_type`)
    REFERENCES `ships` (`record_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systems` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `caption` VARCHAR(24) NOT NULL COMMENT '',
  `x` INT NOT NULL DEFAULT 0 COMMENT '',
  `y` INT NOT NULL DEFAULT 0 COMMENT '',
  `radius` INT NOT NULL DEFAULT 8 COMMENT '',
  `protected` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `race` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  UNIQUE INDEX `caption_UNIQUE` (`caption` ASC)  COMMENT '',
  UNIQUE INDEX `system_xy` (`y` ASC, `x` ASC)  COMMENT '',
  INDEX `fk_system_race_idx` (`race` ASC)  COMMENT '',
  CONSTRAINT `fk_system_race`
    FOREIGN KEY (`race`)
    REFERENCES `races` (`record_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `place_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `place_types` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `caption` VARCHAR(16) NOT NULL COMMENT '',
  `port_goods` INT NULL DEFAULT 0 COMMENT '',
  `deploy_solar_collectors` INT NULL DEFAULT 0 COMMENT '',
  `deploy_bases` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  UNIQUE INDEX `caption_UNIQUE` (`caption` ASC)  COMMENT '',
  INDEX `place_deploy_ports` (`port_goods` ASC)  COMMENT '',
  INDEX `place_deploy_solar` (`deploy_solar_collectors` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `places` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `caption` VARCHAR(24) NOT NULL COMMENT '',
  `system` INT NULL COMMENT '',
  `x` INT NOT NULL DEFAULT 0 COMMENT '',
  `y` INT NOT NULL DEFAULT 0 COMMENT '',
  `type` INT NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fk_location_places_idx` (`system` ASC)  COMMENT '',
  INDEX `fk_place_type_idx` (`type` ASC)  COMMENT '',
  INDEX `fk_places_xy` (`y` ASC, `x` ASC)  COMMENT '',
  UNIQUE INDEX `fk_unique_place` (`type` ASC, `y` ASC, `x` ASC)  COMMENT '',
  CONSTRAINT `fk_system_places`
    FOREIGN KEY (`system`)
    REFERENCES `systems` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_place_type`
    FOREIGN KEY (`type`)
    REFERENCES `place_types` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(24) NOT NULL COMMENT '',
  `password1` VARCHAR(256) NOT NULL COMMENT '',
  `password2` VARCHAR(256) NOT NULL COMMENT '',
  `session_id` VARCHAR(128) NULL COMMENT '',
  `session_time` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_players` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user` INT NULL COMMENT '',
  `player` INT NULL COMMENT '',
  `session_id` VARCHAR(128) NULL COMMENT '',
  `session_time` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  UNIQUE INDEX `idx_user_player` (`user` ASC, `player` ASC)  COMMENT '',
  INDEX `fk_up_players_idx` (`player` ASC)  COMMENT '',
  CONSTRAINT `fk_up_users`
    FOREIGN KEY (`user`)
    REFERENCES `users` (`record_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_up_players`
    FOREIGN KEY (`player`)
    REFERENCES `players` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goods` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `caption` VARCHAR(24) NOT NULL COMMENT '',
  `level` INT NOT NULL DEFAULT 1 COMMENT '',
  `race` INT NULL DEFAULT NULL COMMENT '',
  `tech` INT NULL DEFAULT 0 COMMENT '',
  `type` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  UNIQUE INDEX `caption_UNIQUE` (`caption` ASC)  COMMENT '',
  INDEX `goods_level` (`level` ASC)  COMMENT '',
  INDEX `fk_goods_race_idx` (`race` ASC)  COMMENT '',
  CONSTRAINT `fk_goods_race`
    FOREIGN KEY (`race`)
    REFERENCES `races` (`record_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordnance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordnance` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `system` INT NOT NULL COMMENT '',
  `x` INT NULL DEFAULT 0 COMMENT '',
  `y` INT NULL DEFAULT 0 COMMENT '',
  `good` INT NOT NULL COMMENT '',
  `amount` INT NULL DEFAULT 0 COMMENT '',
  `owner` INT NOT NULL COMMENT '',
  `alliance` INT NULL COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fk_ordnance_system_idx` (`system` ASC)  COMMENT '',
  INDEX `fk_ordnance_owner_idx` (`owner` ASC)  COMMENT '',
  INDEX `ordnance_xy` (`y` ASC, `x` ASC)  COMMENT '',
  INDEX `fk_ordnance_alliance_idx` (`alliance` ASC)  COMMENT '',
  INDEX `fk_ordnance_good_idx` (`good` ASC)  COMMENT '',
  INDEX `fk_amount` (`amount` ASC)  COMMENT '',
  CONSTRAINT `fk_ordnance_alliance`
    FOREIGN KEY (`alliance`)
    REFERENCES `alliances` (`record_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ordnance_good`
    FOREIGN KEY (`good`)
    REFERENCES `goods` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ordnance_owner`
    FOREIGN KEY (`owner`)
    REFERENCES `players` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ordnance_system`
    FOREIGN KEY (`system`)
    REFERENCES `systems` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_fields`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_fields` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user` INT NULL COMMENT '',
  `group` VARCHAR(16) NOT NULL COMMENT '',
  `key` VARCHAR(16) NOT NULL COMMENT '',
  `value` VARCHAR(64) NOT NULL COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fk_user_flags_idx` (`user` ASC)  COMMENT '',
  UNIQUE INDEX `fk_group_key` USING BTREE (`group` ASC, `key` ASC, `user` ASC)  COMMENT '',
  CONSTRAINT `fk_user_flags`
    FOREIGN KEY (`user`)
    REFERENCES `users` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `item_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `item_types` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `caption` VARCHAR(16) NOT NULL COMMENT '',
  `max_stock` INT NOT NULL DEFAULT 15000 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  UNIQUE INDEX `caption_UNIQUE` (`caption` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dealer_inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dealer_inventory` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `place` INT NOT NULL COMMENT '',
  `item_type` INT NOT NULL COMMENT '',
  `item` INT NULL COMMENT '',
  `stock` INT NULL DEFAULT 0 COMMENT '',
  `price` INT NULL DEFAULT 0 COMMENT '',
  `last_update` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fk_item_type_idx` (`item_type` ASC)  COMMENT '',
  INDEX `fk_dealer_place_idx` (`place` ASC)  COMMENT '',
  CONSTRAINT `fk_item_type`
    FOREIGN KEY (`item_type`)
    REFERENCES `item_types` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dealer_place`
    FOREIGN KEY (`place`)
    REFERENCES `places` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `player_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `player_cargo` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `player` INT NULL COMMENT '',
  `good` INT NULL COMMENT '',
  `amount` INT NOT NULL DEFAULT 0 COMMENT '',
  `bought` INT NULL DEFAULT 0 COMMENT '',
  `sold` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fk_player_cargo_id_idx` (`player` ASC)  COMMENT '',
  INDEX `fk_player_cargo_goods_idx` (`good` ASC)  COMMENT '',
  CONSTRAINT `fk_player_cargo_id`
    FOREIGN KEY (`player`)
    REFERENCES `players` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_player_cargo_goods`
    FOREIGN KEY (`good`)
    REFERENCES `goods` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `port_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `port_goods` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `place` INT NULL COMMENT '',
  `good` INT NULL COMMENT '',
  `amount` INT NULL DEFAULT 0 COMMENT '',
  `distance` INT NULL DEFAULT 0 COMMENT '',
  `upgrade` INT NULL DEFAULT 0 COMMENT '',
  `supply` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `last_update` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fk_port_good_idx` (`good` ASC)  COMMENT '',
  INDEX `fk_port_place_idx` (`place` ASC)  COMMENT '',
  CONSTRAINT `fk_port_good`
    FOREIGN KEY (`good`)
    REFERENCES `goods` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_port_place`
    FOREIGN KEY (`place`)
    REFERENCES `places` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warps` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `place` INT NOT NULL COMMENT '',
  `x` INT NULL COMMENT 'Destination',
  `y` INT NULL COMMENT 'Destination',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fkey_warp_place_idx` (`place` ASC)  COMMENT '',
  CONSTRAINT `fkey_warp_place`
    FOREIGN KEY (`place`)
    REFERENCES `places` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `start_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `start_goods` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `place_type` INT NOT NULL COMMENT '',
  `good` INT NOT NULL COMMENT '',
  `percent` INT NOT NULL DEFAULT 100 COMMENT '',
  `supply` INT NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fkey_start_goods_place_idx` (`place_type` ASC)  COMMENT '',
  INDEX `fkey_start_goods_idx` (`good` ASC)  COMMENT '',
  CONSTRAINT `fkey_start_goods_place`
    FOREIGN KEY (`place_type`)
    REFERENCES `place_types` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkey_start_goods`
    FOREIGN KEY (`good`)
    REFERENCES `goods` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `good_upgrades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `good_upgrades` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `good` INT NOT NULL COMMENT '',
  `target` INT NOT NULL COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fkey_good_upgrades_idx` (`good` ASC)  COMMENT '',
  INDEX `fkey_good_upgrade_target_idx` (`target` ASC)  COMMENT '',
  CONSTRAINT `fkey_good_upgrade_source`
    FOREIGN KEY (`good`)
    REFERENCES `goods` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkey_good_upgrade_target`
    FOREIGN KEY (`target`)
    REFERENCES `goods` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `player_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `player_log` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `player` INT NOT NULL COMMENT '',
  `action` INT NOT NULL COMMENT '',
  `target` INT NULL DEFAULT 0 COMMENT '',
  `amount1` INT NULL DEFAULT 0 COMMENT '',
  `amount2` INT NULL DEFAULT 0 COMMENT '',
  `timestamp` INT NOT NULL COMMENT '',
  `reconciled` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fkey_player_log_players_idx` (`player` ASC)  COMMENT '',
  INDEX `idx_player_log_reconciled` (`reconciled` ASC)  COMMENT '',
  CONSTRAINT `fkey_player_log_players`
    FOREIGN KEY (`player`)
    REFERENCES `players` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alliance_invitations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alliance_invitations` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `alliance` INT NOT NULL COMMENT '',
  `player` INT NOT NULL COMMENT '',
  `requested` INT NOT NULL DEFAULT 0 COMMENT '',
  `rejected` INT NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `pk_alliance_invite_idx` (`alliance` ASC)  COMMENT '',
  INDEX `pk_alliance_player_invite_idx` (`player` ASC)  COMMENT '',
  CONSTRAINT `pk_alliance_invite`
    FOREIGN KEY (`alliance`)
    REFERENCES `alliances` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pk_alliance_player_invite`
    FOREIGN KEY (`player`)
    REFERENCES `players` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bases` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `owner` INT NULL DEFAULT NULL COMMENT '',
  `alliance` INT NULL DEFAULT NULL COMMENT '',
  `seed` INT NOT NULL DEFAULT 0 COMMENT '',
  `last_update` INT NOT NULL DEFAULT 0 COMMENT '',
  `shields` INT NOT NULL DEFAULT 1000 COMMENT '',
  `place` INT NOT NULL COMMENT '',
  `max_shields` INT NOT NULL DEFAULT 1000 COMMENT '',
  `shield_production` INT NOT NULL DEFAULT 1 COMMENT '',
  `power` INT NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fk_base_owner_idx` (`owner` ASC)  COMMENT '',
  INDEX `fk_base_alliance_idx` (`alliance` ASC)  COMMENT '',
  INDEX `fk_base_place_idx` (`place` ASC)  COMMENT '',
  CONSTRAINT `fk_base_owner`
    FOREIGN KEY (`owner`)
    REFERENCES `players` (`record_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_base_alliance`
    FOREIGN KEY (`alliance`)
    REFERENCES `alliances` (`record_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_base_place`
    FOREIGN KEY (`place`)
    REFERENCES `places` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `room_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `room_types` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `caption` VARCHAR(24) NULL COMMENT '',
  `width` INT NULL DEFAULT 3 COMMENT '',
  `height` INT NULL DEFAULT 3 COMMENT '',
  `floor_mask` BIGINT NULL DEFAULT 0 COMMENT '',
  `wall_mask` BIGINT NULL DEFAULT 0 COMMENT '',
  `can_rotate` TINYINT NULL DEFAULT 0 COMMENT '',
  `hit_points` INT NULL DEFAULT 1000 COMMENT '',
  `build_time` INT NULL DEFAULT 300 COMMENT '',
  `build_cost` INT NULL DEFAULT 100000 COMMENT '',
  `build_limit` INT NULL DEFAULT 1 COMMENT '',
  `turn_cost` DECIMAL(6,1) NULL DEFAULT 1.0 COMMENT '',
  `can_land` TINYINT NULL DEFAULT 0 COMMENT '',
  `power` INT NULL DEFAULT 0 COMMENT '',
  `good` INT NULL DEFAULT NULL COMMENT '',
  `production` INT NULL DEFAULT 0 COMMENT '',
  `shield_generators` INT NULL DEFAULT 0 COMMENT '',
  `turrets` INT NULL DEFAULT 0 COMMENT '',
  `turret_damage` INT NULL DEFAULT 0 COMMENT '',
  `experience` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fkey_room_good_idx` (`good` ASC)  COMMENT '',
  CONSTRAINT `fkey_room_good`
    FOREIGN KEY (`good`)
    REFERENCES `goods` (`record_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_rooms` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `base` INT NOT NULL COMMENT '',
  `room` INT NOT NULL COMMENT '',
  `x` INT NULL COMMENT '',
  `y` INT NULL COMMENT '',
  `theta` INT NULL DEFAULT 0 COMMENT '0, 1, 2, or 3 for 90 degree rotations',
  `finish_time` INT NULL DEFAULT 0 COMMENT '',
  `damage` INT NULL DEFAULT 0 COMMENT '',
  `last_update` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fkey_room_base_idx` (`base` ASC)  COMMENT '',
  INDEX `fkey_room_type_idx` (`room` ASC)  COMMENT '',
  CONSTRAINT `fkey_room_base`
    FOREIGN KEY (`base`)
    REFERENCES `bases` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkey_room_type`
    FOREIGN KEY (`room`)
    REFERENCES `room_types` (`record_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `research_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `research_items` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `caption` VARCHAR(24) NULL COMMENT '',
  `cost` INT NULL DEFAULT 100000 COMMENT '',
  `turn_cost` INT NULL DEFAULT 1 COMMENT '',
  `time` INT NULL DEFAULT 300 COMMENT '',
  `rank` INT NOT NULL DEFAULT 1 COMMENT '',
  `experience` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fkey_research_rank_idx` (`rank` ASC)  COMMENT '',
  CONSTRAINT `fkey_research_rank`
    FOREIGN KEY (`rank`)
    REFERENCES `ranks` (`record_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gold_keys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gold_keys` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `type` INT NOT NULL DEFAULT 0 COMMENT '',
  `key` VARCHAR(96) NOT NULL COMMENT '',
  `time` INT NOT NULL DEFAULT 2678400 COMMENT '',
  `used` INT NOT NULL DEFAULT 0 COMMENT '',
  `user` INT NULL COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  UNIQUE INDEX `gk_UNIQUE` (`key` ASC)  COMMENT '',
  INDEX `fkey_gold_user_idx` (`user` ASC)  COMMENT '',
  INDEX `fkey_gold_type` (`type` ASC)  COMMENT '',
  INDEX `fkey_gold_used` (`used` ASC)  COMMENT '',
  CONSTRAINT `fkey_gold_user`
    FOREIGN KEY (`user`)
    REFERENCES `users` (`record_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `messages` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `posted` INT NOT NULL DEFAULT 0 COMMENT '',
  `expiration` INT NOT NULL DEFAULT 0 COMMENT '',
  `message` VARCHAR(512) NOT NULL COMMENT '',
  `sender` INT NULL COMMENT '',
  `type` INT NOT NULL DEFAULT 1 COMMENT '',
  `id` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `i_message_timestamp` (`posted` ASC, `expiration` ASC)  COMMENT '',
  INDEX `fk_message_sender_idx` (`sender` ASC)  COMMENT '',
  CONSTRAINT `fk_message_sender`
    FOREIGN KEY (`sender`)
    REFERENCES `players` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `message_targets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `message_targets` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `message` INT NOT NULL COMMENT '',
  `target` INT NOT NULL COMMENT '',
  `read` INT NOT NULL DEFAULT 0 COMMENT '',
  `sender` INT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fkey_target_sender_idx` (`sender` ASC)  COMMENT '',
  INDEX `fkey_target_message_idx` (`message` ASC)  COMMENT '',
  INDEX `fkey_target_player_idx` (`target` ASC)  COMMENT '',
  CONSTRAINT `fkey_target_message`
    FOREIGN KEY (`message`)
    REFERENCES `messages` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkey_target_sender`
    FOREIGN KEY (`sender`)
    REFERENCES `players` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkey_target_player`
    FOREIGN KEY (`target`)
    REFERENCES `players` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `message_ignore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `message_ignore` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `player` INT NOT NULL COMMENT '',
  `ignore` INT NOT NULL COMMENT '',
  `expiration` INT NULL COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fk_ignore_player_idx` (`player` ASC)  COMMENT '',
  INDEX `fk_player_ignore_idx` (`ignore` ASC)  COMMENT '',
  INDEX `fk_player_ignore_expiration` (`expiration` ASC)  COMMENT '',
  CONSTRAINT `fk_ignore_player`
    FOREIGN KEY (`player`)
    REFERENCES `players` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_player_ignore`
    FOREIGN KEY (`ignore`)
    REFERENCES `players` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `headline` VARCHAR(48) NOT NULL COMMENT '',
  `abstract` VARCHAR(128) NOT NULL COMMENT '',
  `article` TEXT NOT NULL COMMENT '',
  `author` INT NULL COMMENT '',
  `live` INT NULL DEFAULT 0 COMMENT '',
  `archive` INT NULL DEFAULT 0 COMMENT '',
  `expiration` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_research`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_research` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `base` INT NOT NULL COMMENT '',
  `research` INT NOT NULL COMMENT '',
  `finish_time` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fkey_research_base_idx` (`base` ASC)  COMMENT '',
  INDEX `fkey_research_item_idx` (`research` ASC)  COMMENT '',
  CONSTRAINT `fkey_research_base`
    FOREIGN KEY (`base`)
    REFERENCES `bases` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkey_research_item`
    FOREIGN KEY (`research`)
    REFERENCES `research_items` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `research_requirements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `research_requirements` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `goal` INT NOT NULL COMMENT '',
  `research` INT NULL DEFAULT NULL COMMENT '',
  `build` INT NULL DEFAULT NULL COMMENT '',
  `good` INT NULL DEFAULT NULL COMMENT '',
  `amount` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fkey_required_goal_idx` (`goal` ASC)  COMMENT '',
  INDEX `fkey_required_research_idx` (`research` ASC)  COMMENT '',
  INDEX `fkey_required_build_idx` (`build` ASC)  COMMENT '',
  INDEX `fkey_required_good_idx` (`good` ASC)  COMMENT '',
  CONSTRAINT `fkey_required_goal`
    FOREIGN KEY (`goal`)
    REFERENCES `research_items` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkey_required_research`
    FOREIGN KEY (`research`)
    REFERENCES `research_items` (`record_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fkey_required_build`
    FOREIGN KEY (`build`)
    REFERENCES `room_types` (`record_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fkey_required_good`
    FOREIGN KEY (`good`)
    REFERENCES `goods` (`record_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `room_requirements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `room_requirements` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `room` INT NOT NULL COMMENT '',
  `build` INT NULL DEFAULT NULL COMMENT '',
  `research` INT NULL DEFAULT NULL COMMENT '',
  `good` INT NULL DEFAULT NULL COMMENT '',
  `amount` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fk_room_upgrade_idx` (`room` ASC)  COMMENT '',
  INDEX `fk_upgrade_room_idx` (`build` ASC)  COMMENT '',
  INDEX `fk_room_research_idx` (`research` ASC)  COMMENT '',
  INDEX `fk_room_good_idx` (`good` ASC)  COMMENT '',
  CONSTRAINT `fk_room_upgrade`
    FOREIGN KEY (`room`)
    REFERENCES `room_types` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_upgrade_room`
    FOREIGN KEY (`build`)
    REFERENCES `room_types` (`record_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_room_research`
    FOREIGN KEY (`research`)
    REFERENCES `base_research` (`record_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_room_good`
    FOREIGN KEY (`good`)
    REFERENCES `goods` (`record_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weapons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weapons` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `caption` VARCHAR(24) NOT NULL COMMENT '',
  `good` INT NOT NULL DEFAULT 0 COMMENT '',
  `race` INT NULL DEFAULT NULL COMMENT '',
  `racks` INT NULL DEFAULT 0 COMMENT '',
  `stations` INT NULL DEFAULT 0 COMMENT '',
  `accuracy` DECIMAL(3,2) NULL DEFAULT 1.00 COMMENT '',
  `volley` INT NULL DEFAULT 1 COMMENT '',
  `ammunition` INT NULL DEFAULT NULL COMMENT '',
  `general_damage` INT NULL DEFAULT 0 COMMENT '',
  `shield_damage` INT NULL DEFAULT 0 COMMENT '',
  `armor_damage` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  UNIQUE INDEX `caption_UNIQUE` (`caption` ASC)  COMMENT '',
  INDEX `fkey_weapon_race_idx` (`race` ASC)  COMMENT '',
  INDEX `fkey_weapon_ammo_idx` (`ammunition` ASC)  COMMENT '',
  INDEX `fkey_weapon_good_idx` (`good` ASC)  COMMENT '',
  CONSTRAINT `fkey_weapon_race`
    FOREIGN KEY (`race`)
    REFERENCES `races` (`record_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fkey_weapon_ammo`
    FOREIGN KEY (`ammunition`)
    REFERENCES `goods` (`record_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fkey_weapon_good`
    FOREIGN KEY (`good`)
    REFERENCES `goods` (`record_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solutions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solutions` (
  `record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `player` INT NOT NULL COMMENT '',
  `weapon` INT NOT NULL COMMENT '',
  `ship` INT NOT NULL COMMENT '',
  `group` INT NOT NULL DEFAULT 0 COMMENT '',
  `sequence` INT NOT NULL DEFAULT 0 COMMENT '',
  `fire_time` INT NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`record_id`)  COMMENT '',
  INDEX `fk_solution_player_idx` (`player` ASC)  COMMENT '',
  INDEX `fk_solution_weapon_idx` (`weapon` ASC)  COMMENT '',
  INDEX `fk_solution_ship_idx` (`ship` ASC)  COMMENT '',
  CONSTRAINT `fk_solution_player`
    FOREIGN KEY (`player`)
    REFERENCES `players` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_solution_weapon`
    FOREIGN KEY (`weapon`)
    REFERENCES `weapons` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_solution_ship`
    FOREIGN KEY (`ship`)
    REFERENCES `ships` (`record_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
